# Configuration File for LobbyCore!
# Made by TheRealKizu :P

# ----- [JOIN LEAVE MESSAGE] -----
# Custom Join and Leave Message Toggle
# Enables and Disables the Join and Leave Message
# Options: true | false | disable
enable-joinandleave: false

# Join Message
# Set's the specified join message!
# & - Color
# {name} - Player Name
# Note: Use & instead of ยง or you will experience errors!
join-message: "&bHi, &e{name}"

# Leave Message
# Set's the specified leave message!
# & - Color
# {name} - Player Name
# Note: Use & instead of ยง or you will experience errors!
leave-message: "&bBye, &e{name}"

# ----- [PROXY] -----
# Enable only proxy join
enable-proxyjoin: false
# Proxy IP
proxy-address: 192.168.0.1
# Kick Message
# Message if player didnt joined on Proxy server
# & - Color
# Note: Use & instead of ยง or you will experience errors!
proxy-kickmessage: "&cPlease join the main server"